### ISSUE TITLE
Enable openjdk for 2.13.1 again

### ISSUE THREAD

**Issue by labra** [weso/utils#15]
For some reason, openjdk fails to compile for scala 2.13.1. [This](https://travis-ci.org/weso/utils/jobs/615414930?utm_medium=notification&utm_source=github_status) is the build that failed.

**Comment by labra** [comment]
It is strange because now it seems to work [here](https://travis-ci.org/labra/utils?utm_medium=notification&utm_source=github_status)...maybe it was just a cache error from travis.

**Comment by thewilly** [comment]
After taking a look seems that the error appears at ```line 519: scala.reflect.internal.FatalError: Error accessing /home/travis/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar```

Taking that into account I would also say that the error comes from a cache error from travis, even though looks strange that such errors raise on travis, I will continue investigating if more errors like this are raised by travis.

**Comment by labra** [comment]
I think it works again now so I close this issue
