### ISSUE TITLE
Codecov integration not working

### ISSUE THREAD

**Issue by thewilly** [weso/utils#7]
Since bb4d033 codecov is raising an error and not processing coverage correctly.

If we go to the coverage webpage of the project we can see that for 79bb81b the coverage was build and proccessed. But the next commit that is receives, bb4d033, was not properly processed.

- 79bb81b was about changes in sutils
- bb4d033 was about added tests

This issue must be fixed prior #4.

**Comment by labra** [comment]
You are right...the problem seems to be when I changed the .travis.yml file to use codecoverage only for scala 2.12.10 with a conditional...and it seems it doesn't upload the statistics.

**Comment by thewilly** [comment]
Yes, just investigating and I'm not sure if the problem is that travis is trying to upload two reports for each push/pr one for scala 2.12.10 and openjdk12 and another for oraclejdk12. Again, not sure but might be the problem, will investigate more if no solution is proposed this afternoon.
